language: node_js
node_js:
- stable
- '6'
- '4'

cache:
  yarn: true

script:
  - yarn test

after_script:
  - git push origin :master
  - yarn build
  - git add .
  - git subtree push --prefix docs/ origin master

